name: CI

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install clang-format and cc65
      run: |
        sudo apt-get update && sudo apt-get install -y clang-format cc65

    - name:
      run: |
        ./travis/check-formatting.sh

    - name:
      run: |
        make
